### PR TITLE
PollBuddy Home Page

### PR DESCRIPTION
**Pull request by AnuC01**
I designed PollBuddy's home page.

### CODE REVIEW

**Comment by hbh7** [comment]
While we're at it, I fixed the react-countdown-now issue since no one else has yet and I already did it locally for testing so I thought I might as well commit it.

**Comment by AnuC01** [comment]
Awesome! @hbh7

**Comment by hbh7** [comment]
I'll see if I can get our PM @burgus7 to merge it this weekend. Perhaps backend too if we're feeling adventurous lol. Not much changed but not really any reason not to either so idk.

**Comment by AnuC01** [comment]
Ok sounds good @hbh7

**Comment by AnuC01** [comment]
Ok I will change them @nbezanis

**Pull request merged**
